### EDA4에서 만든 데이터는 boolean값, str값, int값이 사용되고있다.
### boolean, str값을 int로 매핑시켜주고 필요치 않은 칼럼은 drop하는 과정을 거친다.

In [1]:
import numpy as np
import pandas as pd
import requests
import json
from tqdm import tnrange
import time
from sklearn.model_selection import train_test_split

In [16]:
data = pd.read_pickle('data/saving_data/df_info_EDA4')

In [17]:
data.head()

,blueteamId,bluewin,bluefirstBlood,bluefirstTower,bluefirstInhibitor,bluefirstBaron,bluefirstDragon,bluefirstRiftHerald,bluetowerKills,blueinhibitorKills,...,9stats.win,9teamId,9timeline.creepsPerMinDeltas.0-10,9timeline.creepsPerMinDeltas.10-20,9timeline.goldPerMinDeltas.0-10,9timeline.goldPerMinDeltas.10-20,9timeline.lane,9timeline.xpPerMinDeltas.0-10,9timeline.xpPerMinDeltas.10-20,gameDurationM
0,100,Win,True,False,True,True,True,False,8,1,...,False,200,2.2,1.1,189.7,262.7,BOTTOM,280.7,305.2,24.58
1,100,Fail,False,False,False,False,False,False,1,0,...,True,200,8.6,9.9,369.2,834.7,BOTTOM,326.0,753.0,23.40
2,100,Fail,True,True,False,False,True,False,3,0,...,True,200,6.6,7.2,296.8,524.6,JUNGLE,416.8,516.6,28.70
3,100,Fail,False,False,False,False,True,False,0,0,...,True,200,0.5,NaN,414.5,NaN,NONE,424.5,NaN,16.08
4,100,Win,True,True,True,False,True,True,7,1,...,False,200,6.3,NaN,244.0,NaN,NONE,226.5,NaN,13.53

* boolean 값을 0과 1로 바꿔주기 위해 boolean인 칼럼을 리스트로 만들자.

In [18]:
bool_col_list = ['bluefirstBlood','bluefirstTower','bluefirstInhibitor','bluefirstBaron','bluefirstDragon',
                 'bluefirstRiftHerald',
                 'redfirstBlood','redfirstTower','redfirstInhibitor','redfirstBaron','redfirstDragon',
                 'redfirstRiftHerald',
                 '1stats.win','2stats.win','3stats.win','4stats.win','5stats.win',
                 '6stats.win','7stats.win','8stats.win','9stats.win','10stats.win']

* 다음과 같이 간단하게 True는 1로 False는 0으로 바꿔줄 수 있다.
* 다만, 아래의 방법은 NaN값이 존재하지 않아야 가능하므로 주의

In [19]:
for i in bool_col_list:
    data[i] = data[i].astype('int')

In [20]:
data.head()

,blueteamId,bluewin,bluefirstBlood,bluefirstTower,bluefirstInhibitor,bluefirstBaron,bluefirstDragon,bluefirstRiftHerald,bluetowerKills,blueinhibitorKills,...,9stats.win,9teamId,9timeline.creepsPerMinDeltas.0-10,9timeline.creepsPerMinDeltas.10-20,9timeline.goldPerMinDeltas.0-10,9timeline.goldPerMinDeltas.10-20,9timeline.lane,9timeline.xpPerMinDeltas.0-10,9timeline.xpPerMinDeltas.10-20,gameDurationM
0,100,Win,1,0,1,1,1,0,8,1,...,0,200,2.2,1.1,189.7,262.7,BOTTOM,280.7,305.2,24.58
1,100,Fail,0,0,0,0,0,0,1,0,...,1,200,8.6,9.9,369.2,834.7,BOTTOM,326.0,753.0,23.40
2,100,Fail,1,1,0,0,1,0,3,0,...,1,200,6.6,7.2,296.8,524.6,JUNGLE,416.8,516.6,28.70
3,100,Fail,0,0,0,0,1,0,0,0,...,1,200,0.5,NaN,414.5,NaN,NONE,424.5,NaN,16.08
4,100,Win,1,1,1,0,1,1,7,1,...,0,200,6.3,NaN,244.0,NaN,NONE,226.5,NaN,13.53

In [21]:
data.columns

Index(['blueteamId', 'bluewin', 'bluefirstBlood', 'bluefirstTower',
       'bluefirstInhibitor', 'bluefirstBaron', 'bluefirstDragon',
       'bluefirstRiftHerald', 'bluetowerKills', 'blueinhibitorKills',
       ...
       '9stats.win', '9teamId', '9timeline.creepsPerMinDeltas.0-10',
       '9timeline.creepsPerMinDeltas.10-20', '9timeline.goldPerMinDeltas.0-10',
       '9timeline.goldPerMinDeltas.10-20', '9timeline.lane',
       '9timeline.xpPerMinDeltas.0-10', '9timeline.xpPerMinDeltas.10-20',
       'gameDurationM'],
      dtype='object', length=232)

* 소환사의 협곡에서 사용하지 않는 칼럼들은 삭제해준다.

In [22]:
data.drop(['bluevilemawKills','bluedominionVictoryScore',
           'redvilemawKills','reddominionVictoryScore'], axis=1, inplace=True)

In [23]:
data.head()

,blueteamId,bluewin,bluefirstBlood,bluefirstTower,bluefirstInhibitor,bluefirstBaron,bluefirstDragon,bluefirstRiftHerald,bluetowerKills,blueinhibitorKills,...,9stats.win,9teamId,9timeline.creepsPerMinDeltas.0-10,9timeline.creepsPerMinDeltas.10-20,9timeline.goldPerMinDeltas.0-10,9timeline.goldPerMinDeltas.10-20,9timeline.lane,9timeline.xpPerMinDeltas.0-10,9timeline.xpPerMinDeltas.10-20,gameDurationM
0,100,Win,1,0,1,1,1,0,8,1,...,0,200,2.2,1.1,189.7,262.7,BOTTOM,280.7,305.2,24.58
1,100,Fail,0,0,0,0,0,0,1,0,...,1,200,8.6,9.9,369.2,834.7,BOTTOM,326.0,753.0,23.40
2,100,Fail,1,1,0,0,1,0,3,0,...,1,200,6.6,7.2,296.8,524.6,JUNGLE,416.8,516.6,28.70
3,100,Fail,0,0,0,0,1,0,0,0,...,1,200,0.5,NaN,414.5,NaN,NONE,424.5,NaN,16.08
4,100,Win,1,1,1,0,1,1,7,1,...,0,200,6.3,NaN,244.0,NaN,NONE,226.5,NaN,13.53

In [24]:
data.bluewin = data.bluewin.replace({'Win': 1, 'Fail': 0})
data.redwin = data.redwin.replace({'Win': 1, 'Fail': 0})

In [25]:
data.head()

,blueteamId,bluewin,bluefirstBlood,bluefirstTower,bluefirstInhibitor,bluefirstBaron,bluefirstDragon,bluefirstRiftHerald,bluetowerKills,blueinhibitorKills,...,9stats.win,9teamId,9timeline.creepsPerMinDeltas.0-10,9timeline.creepsPerMinDeltas.10-20,9timeline.goldPerMinDeltas.0-10,9timeline.goldPerMinDeltas.10-20,9timeline.lane,9timeline.xpPerMinDeltas.0-10,9timeline.xpPerMinDeltas.10-20,gameDurationM
0,100,1,1,0,1,1,1,0,8,1,...,0,200,2.2,1.1,189.7,262.7,BOTTOM,280.7,305.2,24.58
1,100,0,0,0,0,0,0,0,1,0,...,1,200,8.6,9.9,369.2,834.7,BOTTOM,326.0,753.0,23.40
2,100,0,1,1,0,0,1,0,3,0,...,1,200,6.6,7.2,296.8,524.6,JUNGLE,416.8,516.6,28.70
3,100,0,0,0,0,0,1,0,0,0,...,1,200,0.5,NaN,414.5,NaN,NONE,424.5,NaN,16.08
4,100,1,1,1,1,0,1,1,7,1,...,0,200,6.3,NaN,244.0,NaN,NONE,226.5,NaN,13.53

* NaN 값들도 0으로 채워서 데이터 타입을 맞출 수 있도록 만들자.
* lane 정보의 NONE 값은 타입을 확인해보면 str이기 때문에 0으로 바뀌지 않는다. 해당 칼럼은 데이터 타입을 int로 바꿀것이 아니기 때문에 괜찮다.

In [32]:
data_fill = data.fillna(0)
data_fill.head()

,blueteamId,bluewin,bluefirstBlood,bluefirstTower,bluefirstInhibitor,bluefirstBaron,bluefirstDragon,bluefirstRiftHerald,bluetowerKills,blueinhibitorKills,...,9stats.win,9teamId,9timeline.creepsPerMinDeltas.0-10,9timeline.creepsPerMinDeltas.10-20,9timeline.goldPerMinDeltas.0-10,9timeline.goldPerMinDeltas.10-20,9timeline.lane,9timeline.xpPerMinDeltas.0-10,9timeline.xpPerMinDeltas.10-20,gameDurationM
0,100,1,1,0,1,1,1,0,8,1,...,0,200,2.2,1.1,189.7,262.7,BOTTOM,280.7,305.2,24.58
1,100,0,0,0,0,0,0,0,1,0,...,1,200,8.6,9.9,369.2,834.7,BOTTOM,326.0,753.0,23.40
2,100,0,1,1,0,0,1,0,3,0,...,1,200,6.6,7.2,296.8,524.6,JUNGLE,416.8,516.6,28.70
3,100,0,0,0,0,0,1,0,0,0,...,1,200,0.5,0.0,414.5,0.0,NONE,424.5,0.0,16.08
4,100,1,1,1,1,0,1,1,7,1,...,0,200,6.3,0.0,244.0,0.0,NONE,226.5,0.0,13.53

* int 컬럼과 str컬럼을 나눠서 파악하고 astype 으로 컬럼들의 type을 맞춰주도록 하자.

In [50]:
integer_list = list(data_fill.columns)
len(integer_list)

228

In [51]:
string_list = ['1timeline.lane','2timeline.lane','3timeline.lane','4timeline.lane','5timeline.lane',
               '6timeline.lane','7timeline.lane','8timeline.lane','9timeline.lane','10timeline.lane']

In [52]:
for i in string_list:
    integer_list.remove(i)
len(integer_list)

218

In [62]:
for i in integer_list:
    data_fill[i] = data_fill[i].astype('float')
for j in string_list:
    data_fill[j] = data_fill[j].astype('str')

In [66]:
data_fill.dtypes

blueteamId                            float64
bluewin                               float64
bluefirstBlood                        float64
bluefirstTower                        float64
bluefirstInhibitor                    float64
bluefirstBaron                        float64
bluefirstDragon                       float64
bluefirstRiftHerald                   float64
bluetowerKills                        float64
blueinhibitorKills                    float64
bluebaronKills                        float64
bluedragonKills                       float64
blueriftHeraldKills                   float64
redteamId                             float64
redwin                                float64
redfirstBlood                         float64
redfirstTower                         float64
redfirstInhibitor                     float64
redfirstBaron                         float64
redfirstDragon                        float64
redfirstRiftHerald                    float64
redtowerKills                         float64
redinhibitorKills                     float64
redbaronKills                         float64
reddragonKills                        float64
redriftHeraldKills                    float64
gameDuration                          float64
10championId                          float64
10participantId                       float64
10stats.assists                       float64
                                       ...
8stats.win                            float64
8teamId                               float64
8timeline.creepsPerMinDeltas.0-10     float64
8timeline.creepsPerMinDeltas.10-20    float64
8timeline.goldPerMinDeltas.0-10       float64
8timeline.goldPerMinDeltas.10-20      float64
8timeline.lane                         object
8timeline.xpPerMinDeltas.0-10         float64
8timeline.xpPerMinDeltas.10-20        float64
9championId                           float64
9participantId                        float64
9stats.assists                        float64
9stats.champLevel                     float64
9stats.deaths                         float64
9stats.goldEarned                     float64
9stats.kills                          float64
9stats.longestTimeSpentLiving         float64
9stats.totalMinionsKilled             float64
9stats.visionScore                    float64
9stats.visionWardsBoughtInGame        float64
9stats.win                            float64
9teamId                               float64
9timeline.creepsPerMinDeltas.0-10     float64
9timeline.creepsPerMinDeltas.10-20    float64
9timeline.goldPerMinDeltas.0-10       float64
9timeline.goldPerMinDeltas.10-20      float64
9timeline.lane                         object
9timeline.xpPerMinDeltas.0-10         float64
9timeline.xpPerMinDeltas.10-20        float64
gameDurationM                         float64
Length: 228, dtype: object

* boolean과 Win Fail도 0과 1로 나타내며 필요치 않은 칼럼은 drop한 최종적인 데이터 형태를 얻어냈다.

In [67]:
'''
저장
'''
data_fill.to_pickle('data/saving_data/data_info_float.pkl')

In [68]:
'''
저장 데이터 불러오기 확인
'''
loading_test = pd.read_pickle('data/saving_data/data_info_float.pkl')
loading_test.head()

,blueteamId,bluewin,bluefirstBlood,bluefirstTower,bluefirstInhibitor,bluefirstBaron,bluefirstDragon,bluefirstRiftHerald,bluetowerKills,blueinhibitorKills,...,9stats.win,9teamId,9timeline.creepsPerMinDeltas.0-10,9timeline.creepsPerMinDeltas.10-20,9timeline.goldPerMinDeltas.0-10,9timeline.goldPerMinDeltas.10-20,9timeline.lane,9timeline.xpPerMinDeltas.0-10,9timeline.xpPerMinDeltas.10-20,gameDurationM
0,100.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,8.0,1.0,...,0.0,200.0,2.2,1.1,189.7,262.7,BOTTOM,280.7,305.2,24.58
1,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,200.0,8.6,9.9,369.2,834.7,BOTTOM,326.0,753.0,23.40
2,100.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,3.0,0.0,...,1.0,200.0,6.6,7.2,296.8,524.6,JUNGLE,416.8,516.6,28.70
3,100.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,200.0,0.5,0.0,414.5,0.0,NONE,424.5,0.0,16.08
4,100.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,7.0,1.0,...,0.0,200.0,6.3,0.0,244.0,0.0,NONE,226.5,0.0,13.53